### ISSUE TITLE
Add python3-pip dependency installation task

### ISSUE THREAD

**Issue by padawanmohamed** [ebarault/ansible-role-gitlab-runner-docker#2]
I got the following error:
`FAILED! => {"changed": false, "msg": "Unable to find any of pip3 to use.  pip needs to be installed."}`
I solved the error by installing the python3-pip in pre-tasks in my playbook:
```
pre_tasks:
    - name: install python3-pip
      package:
        name: python3-pip
        state: present
```
